[tasks.ci]
description = "task for CI"
command = "cargo"
args = ["check", "--all-targets"]

[tasks.release]
description = "release build and setcap"
command = "sudo"
args = ["setcap", "cap_sys_admin+ep", "./exec"]
dependencies = ["cp"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.cp]
command = "cp"
args = ["./target/release/exec", "./target/release/analyze", "./"]
dependencies = ["build"]
